name: Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  Release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ensure Changelog
        shell: bash
        run: |
          TAG="${GITHUB_REF##*/}"

          if [[ -z "$(grep "^## .*${TAG}" CHANGELOG.md)" ]]; then
            echo "::error ::Could not find ${TAG} in CHANGELOG.md, release halted."
            exit 1
          fi

      - name: Compile Updater
        id: ahk2exe
        uses: cennis91/action-ahk2exe@main
        with:
          in: src/updater.ahk
          out: src/package-updater.exe
          icon: res/icon.ico
          cp: 65001

      - name: Archive Package
        shell: bash
        run: |
          mkdir -p build
          git archive --format=zip --output="build/${GITHUB_REPOSITORY##*/}.zip" HEAD
          (cd "build" && sha1sum "${GITHUB_REPOSITORY##*/}.zip" > sha1sum.txt)

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            CHANGELOG.md
            build/package-updater.zip
            build/sha1sum.txt
            src/package-updater.exe
